spring.application.name=microservicio-transacciones
server.port=8082

# Conexión MariaDB (Puerto 3307)
spring.datasource.url=jdbc:mariadb://localhost:3307/eurekabank?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA Config
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Configuración de log para ver errores de Feign
logging.level.ec.edu.monster.transacciones.clients=DEBUG